"""add ondelete cascade

Revision ID: b5ef4ecfdb64
Revises: 4a367fcf7873
Create Date: 2026-07-30 13:45:32.117661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ef4ecfdb64'
down_revision: Union[str, Sequence[str], None] = '4a367fcf7873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_timeslot_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'timeslots', ['timeslot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('timeslots_room_id_fkey'), 'timeslots', type_='foreignkey')
    op.create_foreign_key(None, 'timeslots', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeslots', type_='foreignkey')
    op.create_foreign_key(op.f('timeslots_room_id_fkey'), 'timeslots', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_timeslot_id_fkey'), 'bookings', 'timeslots', ['timeslot_id'], ['id'])
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
